ktor:
  application:
    modules:
      - eventer.project.ApplicationKt.module
  deployment:
    port: 8080

db:
  driver: "org.postgresql.Driver"
  jdbcUrl: "jdbc:postgresql://localhost:5432/agenda_app"
  username: "postgres"
  password: "XXmamstte12"

oauth:
  google:
    callbackUrl: "https://eventer-backend-03a571f9a14b.herokuapp.com/oauth/google/callback"
  microsoft:
    callbackUrl: "https://eventer-backend-03a571f9a14b.herokuapp.com/oauth/microsoft/callback"